name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - run: npm ci

      # Step 4: Start Vite with proper host binding
      - name: Start Vite
        run: |
          npm run dev -- --host 0.0.0.0 &
          echo "Starting Vite server..."
        env:
          NODE_ENV: test
          VITE_PORT: 5173

      # Step 5: Wait for Vite server with health check
      - name: Wait for Vite server
        run: |
          attempt_counter=0
          max_attempts=30
          
          until $(curl --output /dev/null --silent --head --fail http://localhost:5173); do
            if [ ${attempt_counter} -eq ${max_attempts} ]; then
              echo "Max attempts reached. Vite server is not running."
              cat vite.log
              exit 1
            fi
            
            attempt_counter=$(($attempt_counter+1))
            echo "Waiting for Vite server... (${attempt_counter}/${max_attempts})"
            sleep 2
          done

      # Step 6: Install Cypress dependencies
      - name: Install Cypress
        run: npm install cypress

      # Step 7: Run Cypress Tests
      - name: Run Cypress Tests
        env:
          CYPRESS_BASE_URL: http://localhost:5173
        run: npx cypress run --spec "cypress/e2e/home/home.cy.ts"

      # Step 8: Cleanup
      - name: Cleanup
        if: always()
        run: |
          pkill -f vite || true