name: CI
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          # Install client dependencies
          cd packages/client
          npm ci
          npm install -g vercel
          # Install API dependencies
          cd api
          npm ci
          cd ..

      # DEBUG env vars
      - name: Debug Environment
        run: |
          echo "Checking environment variables..."
          echo "VITE_API_SECRET_KEY exists: ${{ secrets.VITE_API_SECRET_KEY != '' }}"
          echo "Token length: ${#VERCEL_TOKEN}"          
        env:
          VITE_API_SECRET_KEY: ${{ secrets.VITE_API_SECRET_KEY }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      # Step 4: Configure Vercel
      - name: Configure Vercel
        run: |
          # Pull Vercel configuration
          vercel pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}
          vercel env pull --environment=development --token=${{ secrets.VERCEL_TOKEN }}
          # Create or update vercel.json if needed
          echo '{
            "version": 2,
            "builds": [
              { "src": "api/**/*.js", "use": "@vercel/node" },
              { "src": "package.json", "use": "@vercel/static-build" }
            ],
            "routes": [
              { "src": "/api/(.*)", "dest": "api/$1" }
            ]
          }' > vercel.json
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      # Step 5: Start Vercel Dev Server
      - name: Start Vercel Dev Server
        run: |
          vercel dev --yes --token=${{ secrets.VERCEL_TOKEN }} &
          echo "Starting Vercel dev server..."

      # Debug that the proxy is running and we can get event data
      - name: Debug Proxy Setup
        run: |
          echo "Checking API setup..."
          ls -la packages/client/api/
          echo "Checking node_modules in API directory..."
          ls -la packages/client/api/node_modules || echo "No node_modules found!"
          echo "Testing proxy endpoint..."
          curl -v "http://localhost:3000/api/proxy?apiUrl=https%3A%2F%2Fb2c2-events-api.vercel.app%2Fapi%2FgetEventsByType&params=%7B%22type%22%3A%22road%22%7D"

      # Step 6: Wait for Vercel server
      - name: Wait for Vercel server
        run: |
          attempt_counter=0
          max_attempts=100
          
          until $(curl --output /dev/null --silent --head --fail http://localhost:3000); do
            if [ ${attempt_counter} -eq ${max_attempts} ]; then
              echo "Max attempts reached. Vercel server is not running."
              exit 1
            fi
            
            attempt_counter=$(($attempt_counter+1))
            echo "Waiting for Vercel server... (${attempt_counter}/${max_attempts})"
            sleep 2
          done
          
          echo "Vercel server is up!"

      # Step 7: Start Vite
      - name: Start Vite
        env:
          VITE_API_SECRET_KEY: ${{ secrets.VITE_API_SECRET_KEY }}
          # Add any other needed environment variables
        run: |
          cd packages/client
          npm run dev &
          echo "Starting Vite server..."

      # Step 8: Wait for Vite server
      - name: Wait for Vite server
        run: |
          attempt_counter=0
          max_attempts=30
          
          until $(curl --output /dev/null --silent --head --fail http://localhost:5173); do
            if [ ${attempt_counter} -eq ${max_attempts} ]; then
              echo "Max attempts reached. Vite server is not running."
              exit 1
            fi
            
            attempt_counter=$(($attempt_counter+1))
            echo "Waiting for Vite server... (${attempt_counter}/${max_attempts})"
            sleep 2
          done
          
          echo "Vite server is up!"

      # Step 9: Install Cypress
      - name: Install Cypress
        run: |
          cd packages/client
          npm install cypress

      # DEBUGGING
      - name: Debug Server State
        run: |
          echo "Checking server states..."
          echo "Vite Server Response:"
          curl -v http://localhost:5173 || true
          echo "Vercel Server Response:"
          curl -v http://localhost:3000 || true
          echo "Environment Variables:"
          env | grep VITE || true
          env | grep VERCEL || true

      # Step 10: Run Cypress Tests
      - name: Run Cypress Tests
        env:
          CYPRESS_BASE_URL: http://localhost:5173
        run: |
          cd packages/client
          # Check both servers are responding
          echo "Checking Vite server..."
          curl -v http://localhost:5173
          echo "Checking Vercel server..."
          curl -v http://localhost:3000
          # Run tests with more verbose output
          CYPRESS_DEBUG=1 npx cypress run --spec "cypress/e2e/home/home.cy.ts"

      # Step 11: Cleanup
      - name: Cleanup
        if: always()
        run: |
          cd packages/client
          pkill -f "vite" || true
          pkill -f "vercel dev" || true