name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - run: npm ci

      # Step 4: Start Vite in the background
      - name: Start Vite
        run: npm run dev & # Start Vite in the background
        env:
          NODE_ENV: test

      # Step 5: Wait for the Vite server to be ready
      - name: Wait for localhost to be ready
        run: npx wait-on http://localhost:5173

      # Step 6: Install Cypress dependencies
      - name: Install Cypress
        run: npm install cypress

      # Step 7: Run Cypress Tests
      - name: Run Cypress Tests
        env:
          CYPRESS_BASE_URL: http://localhost:5173
        run: npx cypress run --spec "cypress/e2e/home/home.cy.ts"
